spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/center-backend
    username: root
    password: 123456
  session:
    timeout: 86400

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cors:
  allowed-origins:
    # 本地开发调试时可以添加本地地址，但生产环境务必去除
    - http://localhost:8080